version: '3.4'

services:

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    hostname: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./docker_services/mosquitto:/etc/mosquitto
      - ./docker_services/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf