# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages/midi.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages/midi.proto',
  package='midi',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13messages/midi.proto\x12\x04midi\"E\n\x0bInitMessage\x12\x10\n\x08midiFile\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x02\x12\x11\n\tntpOffset\x18\x03 \x01(\x02\x62\x06proto3'
)




_INITMESSAGE = _descriptor.Descriptor(
  name='InitMessage',
  full_name='midi.InitMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='midiFile', full_name='midi.InitMessage.midiFile', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='midi.InitMessage.timestamp', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ntpOffset', full_name='midi.InitMessage.ntpOffset', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=98,
)

DESCRIPTOR.message_types_by_name['InitMessage'] = _INITMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InitMessage = _reflection.GeneratedProtocolMessageType('InitMessage', (_message.Message,), {
  'DESCRIPTOR' : _INITMESSAGE,
  '__module__' : 'messages.midi_pb2'
  # @@protoc_insertion_point(class_scope:midi.InitMessage)
  })
_sym_db.RegisterMessage(InitMessage)


# @@protoc_insertion_point(module_scope)
