version: '3.4'

services:
  # admin:public
  manager:
    image: emqx/ekuiper-manager
    container_name: ekuiper-manager
    ports:
      - "9082:9082"
    restart: unless-stopped
    environment:
      # setting default eKuiper service, works since 1.8.0
      DEFAULT_EKUIPER_ENDPOINT: "http://ekuiper:9081"

  ekuiper:
    image: lfedge/ekuiper
    ports:
      - "9081:9081"
      - "127.0.0.1:20498:20498"
    container_name: ekuiper
    hostname: ekuiper
    restart: unless-stopped
    user: root
    volumes:
      - ./docker_services/kuiper/data:/kuiper/data
      - ./docker_services/kuiper/log:/kuiper/log
    environment:
      MQTT_SOURCE__DEFAULT__SERVER: "tcp://mosquitto:1883"
      KUIPER__BASIC__CONSOLELOG: "true"
      KUIPER__BASIC__IGNORECASE: "false"

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    hostname: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./docker_services/mosquitto:/etc/mosquitto
      - ./docker_services/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf